"""Add assessment duration_minutes for exam paper export

Revision ID: 58e0f0d753a8
Revises: a41902e022ec
Create Date: 2026-08-19 16:43:29.655687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e0f0d753a8'
down_revision: Union[str, None] = 'a41902e022ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.create_check_constraint('ck_assessment_duration_minutes', 'assessments', 'duration_minutes IS NULL OR duration_minutes > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_assessment_duration_minutes', 'assessments', type_='check')
    op.drop_column('assessments', 'duration_minutes')
    # ### end Alembic commands ###
